name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build tests
        run: make agent-tests
      - name: Run tests
        run: ./agent-tests
      - name: Build CLI
        run: make cpp-agent
